import {
  ArrowRight,
  Terminal,
  Map,
  Eye,
  GitBranch,
  AlertCircle,
} from "lucide-react";

export default function TrustAuthority3() {
  return (
    <section id="trust-authority" className="py-10 relative overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(0,255,0,0.03),transparent_50%)]" />

      <div className="container mx-auto px-6 relative">
        <div className="max-w-4xl mx-auto text-center mb-20">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-secondary/50 border border-border/50 mb-8">
            <Terminal className="w-4 h-4 text-green-500" />
            <span className="text-sm font-mono text-muted-foreground">
              root@trust:~# whoami
            </span>
          </div>

          <h1 className="font-aeonik text-4xl sm:text-5xl md:text-7xl font-bold text-foreground mb-6 leading-tight">
            We see what attackers see.
          </h1>

          <p className="text-xl sm:text-2xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Before they do. Before it costs you.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-12 items-center mb-24">
          <div className="relative">
            <div className="absolute -inset-4 bg-linear-to-r from-red-500/10 to-transparent rounded-3xl blur-2xl" />
            <div className="relative bg-card border border-border/30 rounded-2xl p-1">
              <div className="bg-secondary/30 rounded-xl p-4 font-mono text-sm">
                <div className="flex items-center gap-2 text-green-500 mb-3">
                  <span>$</span>
                  <span>cat /var/log/attack-surface.log</span>
                </div>
                <div className="space-y-2 text-muted-foreground">
                  <p>[2024-03-15] Unauthenticated RCE in auth-service v2.1.3</p>
                  <p>
                    [2024-03-15] Exploit chain: SSRF → Internal metadata →
                    PrivEsc
                  </p>
                  <p className="text-yellow-500">
                    [2024-03-15] CRITICAL: No logs generated by target
                  </p>
                  <p>[2024-03-16] Vendor notified (CVE-2024-XXXX)</p>
                  <p className="text-green-500">
                    [2024-03-17] Patch deployed to all clients
                  </p>
                </div>
              </div>
            </div>

            <div className="absolute -bottom-4 -right-4 bg-primary text-primary-foreground px-6 py-3 rounded-full shadow-2xl">
              <span className="text-sm font-mono">0-day → patch: 48hrs</span>
            </div>
          </div>

          <div className="space-y-6">
            <div className="inline-flex items-center gap-2 text-sm text-muted-foreground uppercase tracking-wider">
              <AlertCircle className="w-4 h-4 text-red-500" />
              <span>Real story. March 2024.</span>
            </div>
            <h2 className="font-aeonik text-3xl sm:text-4xl font-bold text-foreground">
              We find what scanners can&apos;t.
            </h2>
            <p className="text-lg text-muted-foreground">
              A major fintech&apos;s authentication service had been vulnerable
              for 18 months. No scanner detected it. No auditor flagged it. We
              found it in 4 hours.
            </p>
            <div className="flex flex-wrap gap-4 pt-4">
              {["Business logic flaw", "Zero logs", "Production impact"].map(
                (tag) => (
                  <span
                    key={tag}
                    className="text-xs px-3 py-1.5 rounded-full bg-red-500/10 text-red-500 border border-red-500/20"
                  >
                    {tag}
                  </span>
                ),
              )}
            </div>
          </div>
        </div>

        <div className="mb-24">
          <div className="text-center mb-12">
            <h2 className="font-aeonik text-3xl sm:text-4xl font-bold text-foreground mb-4">
              The attacker&apos;s journey
            </h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              We don&apos;t follow checklists. We follow the path of least
              resistance.
            </p>
          </div>

          <div className="relative">
            <div className="absolute left-0 right-0 top-1/2 h-px bg-linear-to-r from-transparent via-border to-transparent hidden lg:block" />

            <div className="grid grid-cols-1 lg:grid-cols-4 items-stretch gap-4">
              {[
                {
                  phase: "Reconnaissance",
                  desc: "OSINT, dark web, leaked credentials, exposed APIs",
                  icon: Map,
                  color: "text-blue-500",
                },
                {
                  phase: "Weaponization",
                  desc: "Custom exploits, payload crafting, evasion techniques",
                  icon: GitBranch,
                  color: "text-purple-500",
                },
                {
                  phase: "Breach",
                  desc: "Initial access, persistence, defense evasion",
                  icon: Eye,
                  color: "text-red-500",
                },
                {
                  phase: "Impact",
                  desc: "Data exfiltration, ransomware prep, business disruption",
                  icon: AlertCircle,
                  color: "text-orange-500",
                },
              ].map((item, i) => {
                const Icon = item.icon;
                return (
                  <div key={item.phase} className="relative group">
                    <div className="bg-card border border-border/30 rounded-2xl p-6 hover:border-primary/30 transition-all duration-300">
                      <div
                        className={`w-12 h-12 rounded-xl bg-secondary flex items-center justify-center mb-4 ${item.color}`}
                      >
                        <Icon className="w-6 h-6" />
                      </div>
                      <div className="text-sm font-mono text-muted-foreground mb-2">
                        Phase {i + 1}
                      </div>
                      <h3 className="text-lg font-semibold mb-2">
                        {item.phase}
                      </h3>
                      <p className="text-sm text-muted-foreground">
                        {item.desc}
                      </p>
                    </div>

                    {i < 3 && (
                      <div className="hidden lg:block absolute -right-2 top-1/2 transform -translate-y-1/2 z-10">
                        <ArrowRight className="w-4 h-4 text-muted-foreground" />
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        <div className="rounded-3xl border border-border/30 bg-linear-to-br from-secondary/20 to-secondary/5 overflow-hidden mb-24">
          <div className="grid lg:grid-cols-2">
            <div className="p-8 lg:p-12">
              <h2 className="font-aeonik text-3xl sm:text-4xl font-bold text-foreground mb-6">
                Full disclosure. <br />
                No black boxes.
              </h2>
              <p className="text-lg text-muted-foreground mb-6">
                Every finding includes:
              </p>
              <ul className="space-y-4">
                {[
                  "Proof-of-concept code you can verify",
                  "Exploit chain visualization",
                  "Business impact assessment (in $$$)",
                  "Remediation guidance with priority order",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-3">
                    <div className="w-5 h-5 rounded-full bg-green-500/10 flex items-center justify-center mt-0.5">
                      <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                    </div>
                    <span className="text-muted-foreground">{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="relative min-h-75 bg-secondary/30 p-8 lg:p-12 flex items-center">
              <div className="relative w-full">
                <div className="absolute inset-0 bg-linear-to-r from-transparent via-primary/5 to-transparent" />
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-card rounded-xl p-4 border border-border/30">
                    <div className="font-mono text-xs text-green-500 mb-2">
                      exploit.py
                    </div>
                    <div className="space-y-1">
                      <div className="h-2 w-full bg-secondary rounded" />
                      <div className="h-2 w-3/4 bg-secondary rounded" />
                      <div className="h-2 w-full bg-secondary rounded" />
                    </div>
                  </div>
                  <div className="bg-card rounded-xl p-4 border border-border/30">
                    <div className="font-mono text-xs text-blue-500 mb-2">
                      impact.md
                    </div>
                    <div className="space-y-1">
                      <div className="h-2 w-full bg-secondary rounded" />
                      <div className="h-2 w-4/5 bg-secondary rounded" />
                      <div className="h-2 w-full bg-secondary rounded" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
